name: Build Stream Deck Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: serial-usb-commander2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: |
          npm run build
          ls -la com.butzy79.serial-usb-commander2.sdPlugin/bin

      - name: Commit generated plugin
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add com.butzy79.serial-usb-commander2.sdPlugin/bin/plugin.js
          git commit -m "Auto build Stream Deck plugin" || exit 0
          git push