name: Build Stream Deck Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: serial-usb-commander2
        run: npm install

      - name: Build plugin
        working-directory: serial-usb-commander2
        run: npm run build


      - name: Prepare plugin dependencies
        working-directory: serial-usb-commander2/com.butzy79.serial-usb-commander2.sdPlugin
        run: npm install --omit=dev serialport

      - name: Commit generated plugin
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add serial-usb-commander2/com.butzy79.serial-usb-commander2.sdPlugin/bin/plugin.js
          git add serial-usb-commander2/com.butzy79.serial-usb-commander2.sdPlugin/package.json
          git add serial-usb-commander2/com.butzy79.serial-usb-commander2.sdPlugin/package-lock.json
          git add serial-usb-commander2/com.butzy79.serial-usb-commander2.sdPlugin/node_modules

          git commit -m "Auto build Stream Deck plugin" || echo "Nothing to commit"

          git push
      